language: c
matrix:
  include:
    - name: linux x86_64 and i686 / mingw x64 and x32 on Wine
      os: linux
      sudo: required
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-multilib
            - mingw-w64
            - wine64
            - wine32
            - wine-binfmt
      before_script:
        - sudo update-binfmts --import wine
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-linux
        - ./.travis/run-test.sh i686-linux       "CC=gcc -m32"
        - ./.travis/run-test.sh x86_64-mingw32   "CC=x86_64-w64-mingw32-gcc"
        - ./.travis/run-test.sh i686-mingw32     "CC=i686-w64-mingw32-gcc -static-libgcc"
    - name: alpine linux on docker
      os: linux
      dist: bionic
      before_script:
        - docker build -f .travis/Dockerfile-alpine-test -t funchook-test .
      script:
        - docker run --rm funchook-test
    - name: Xcode 11.3 (the latest version)
      os: osx
      osx_image: xcode11.3
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
    - name: Xcode 10.3 (the latest version which can change memory regions in exe)
      os: osx
      osx_image: xcode10.3
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
    - name: Xcode 10.1 (the latest version supporting 32-bit)
      os: osx
      osx_image: xcode10.1
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
        - ./.travis/run-test.sh i686-darwin      "CC=cc -m32"
