language: c
matrix:
  include:
    - os: linux
      sudo: required
      dist: bionic
      addons:
        apt:
          packages:
            - gcc-multilib
            - mingw-w64
            - wine64
            - wine32
            - wine-binfmt
      before_script:
        - sudo update-binfmts --import wine
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-linux
        - ./.travis/run-test.sh i686-linux       "CC=gcc -m32"
        - ./.travis/run-test.sh x86_64-mingw32   "CC=x86_64-w64-mingw32-gcc"
        - ./.travis/run-test.sh i686-mingw32     "CC=i686-w64-mingw32-gcc -static-libgcc"
    - os: osx
      osx_image: xcode9.4  # Xcode 9.4.1 on macOS 10.13 High Sierra
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
        - ./.travis/run-test.sh i686-darwin      "CC=cc -m32"
    - os: osx
      osx_image: xcode10.2 # Xcode 10.2.1 on macOS 10.14 Mojave
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
    - os: osx
      osx_image: xcode10.3 # Xcode 10.3 on macOS 10.14 Mojave
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
    - os: osx
      osx_image: xcode11   # Xcode 11.0 on macOS 10.14 Mojave
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
    - os: osx
      osx_image: xcode11.1 # Xcode 11.1 on macOS 10.14 Mojave
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
    - os: osx
      osx_image: xcode11.2 # Xcode 11.2 on macOS 10.14 Mojave
      script:
        - ./autogen.sh
        - ./.travis/run-test.sh x86_64-darwin
